apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    {{- include "portfolio.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.environment | quote }}
  APP_DEBUG: {{ .Values.config.debug | quote }}
  APP_PORT: {{ .Values.config.port | quote }}
  APP_VERSION: {{ .Chart.AppVersion | quote }}
